# Generated by Django 5.1.6 on 2025-02-23 14:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firstapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='firstappimg')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('superheros', models.CharField(choices=[('MDB', 'Manash Dev Bhatta'), ('SBB', 'Surya Bahadur Bhandari'), ('KK', 'Karna Kumar')], max_length=10)),
            ],
        ),
    ]
