# Generated by Django 5.1.6 on 2025-02-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_firstapp_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firstapp',
            old_name='desc',
            new_name='description',
        ),
    ]
